<?php
return [

    'default' => 'Small Cent',
    /*
    |--------------------------------------------------------------------------
    | All categories
    |--------------------------------------------------------------------------
    |
    | This option controls the default broadcaster that will be used by the
    | framework when an event needs to be broadcast. You may set this to
    | any of the connections defined in the "connections" array below.
    |
    |
    */
    'coinCategories' => [
        'One Hundred Dollar',
        'Fifty Dollar',
        'Twenty Five Dollar',
        'Twenty Dollar',
        'Ten Dollar',
        'Five Dollar',
        'Four Dollar',
        'Three Dollar',
        'Quarter Eagle',
        'Dollar',
        'Gold Dollar',
        'No Coin',
        'Commemorative Dollar',
        'Silver Dollar',
        'Commemorative Half Dollar',
        'Half Dollar',
        'Quarter',
        'Twenty Cent',
        'Dime',
        'Nickel',
        'Half Dime',
        'Three Cent',
        'Two Cent',
        'Large Cent',
        'Small Cent',
        'Half Cent'
    ],
    'snowTypes' => [
        'Indian Head',
        'Flying Eagle'
    ],
    'vamTypes' => [
        'Morgan Dollar',
        'Peace Dollar'
    ],
    'firstDayCats' => [
        'Dollar',
        'Quarter',
        'Nickel'
    ],

    'colorCategories' => [
        'Small Cent',
        'Large Cent',
        'Half Cent'
    ],
    'colorTypes' => [
        'Lincoln Wheat',
        'Lincoln Memorial',
        'Indian Head',
        'Flying Eagle'
    ],

    'bandCategories' => [
        'Roosevelt Dime',
        'Winged Liberty Dime'
    ],

    'sheldonTypes' => [
        'Flowing Hair Large Cent',
        'Liberty Cap Large Cent',
        'Draped Bust Large Cent',
        'Classic Head Large Cent'
    ],

    'newcombTypes' => [
        'Coronet Liberty Head Large Cent',
        'Braided Hair Liberty Head Large Cent'
    ],

    'wexlerTypes' => [
        'Westward Journey',
        'Lincoln Wheat',
        'Lincoln Memorial',
        'Seated Liberty Half Dime',
        'Liberty Cap Dime',
        'Seated Liberty Dime',
        'Barber Dime',
        'Winged Liberty Dime',
        'Roosevelt Dime',
        'Twenty Cent Piece',
        'Liberty Cap Quarter',
        'Seated Liberty Quarter',
        'Barber Quarter',
        'Standing Liberty',
        'Washington Quarter',
        'Seated Liberty Half Dollar',
        'Barber Half Dollar',
        'Walking Liberty',
        'Kennedy Half Dollar',
        'Franklin Half Dollar',
        'Seated Liberty Dollar',
        'Susan B Anthony Dollar',
        'Trade Dollar', 'Morgan Dollar',
        'Peace Dollar',
        'Presidential Dollar',
        'Sacagawea Dollar',
        'Eisenhower Dollar',
        'Liberty Head Gold Dollar',
        'Indian Princess Gold Dollar',
        'Coronet Head Quarter Eagle',
        'Indian Princess Three Dollar',
        'Liberty Cap Half Eagle',
        'Turban Head Half Eagle',
        'Coronet Head Half Eagle',
        'Indian Head Half Eagle',
        'Coronet Head Eagle',
        'Saint Gaudens Double Eagle',
        'Coronet Head Double Eagle',
        'Commemorative Half Dollar',
        'Silver Dollar',
        'Tenth Ounce Gold',
        'Quarter Ounce Gold',
        'Half Ounce Gold',
        'One Ounce Gold',
        'Quarter Ounce Platinum'
    ],

    'trailTypes' => [
        'Lincoln Memorial',
        'Jefferson Nickel',
        'Westward Journey',
        'Return to Monticello',
        'Roosevelt Dime',
        'Washington Quarter',
        'State Quarter',
        'Kennedy Half Dollar',
        'Franklin Half Dollar',
        'Morgan Dollar',
        'Eisenhower Dollar',
        'Sacagawea Dollar',
        'Presidential Dollar'
    ],

    'fsTypes' => ['Lincoln Wheat',
        'Lincoln Memorial',
        'Jefferson Nickel',
        'Liberty Cap Half Dime',
        'Seated Liberty Half Dime',
        'Liberty Cap Dime',
        'Seated Liberty Dime',
        'Barber Dime',
        'Winged Liberty Dime',
        'Roosevelt Dime',
        'Twenty Cent Piece',
        'Liberty Cap Quarter',
        'Seated Liberty Quarter',
        'Barber Quarter',
        'Standing Liberty',
        'Washington Quarter',
        'Seated Liberty Half Dollar',
        'Barber Half Dollar',
        'Walking Liberty',
        'Kennedy Half Dollar',
        'Franklin Half Dollar',
        'Seated Liberty Dollar',
        'Susan B Anthony Dollar',
        'Trade Dollar',
        'Morgan Dollar',
        'Peace Dollar',
        'Presidential Dollar',
        'Sacagawea Dollar',
        'Eisenhower Dollar',
        'Liberty Head Gold Dollar',
        'Indian Princess Gold Dollar',
        'Coronet Head Quarter Eagle',
        'Indian Princess Three Dollar',
        'Liberty Cap Half Eagle',
        'Turban Head Half Eagle',
        'Coronet Head Half Eagle',
        'Indian Head Half Eagle',
        'Coronet Head Eagle',
        'Saint Gaudens Double Eagle',
        'Coronet Head Double Eagle',
        'Commemorative Half Dollar',
        'Silver Dollar',
        'Tenth Ounce Gold',
        'Quarter Ounce Gold',
        'Half Ounce Gold',
        'One Ounce Gold',
        'Quarter Ounce Platinum'
    ],

    'wileyBugertTypes' => [
        'Seated Liberty Half Dime',
        'Seated Liberty Dime',
        'Seated Liberty Quarter',
        'Seated Liberty Half Dollar',
        'Seated Liberty Dollar'
    ],

    'varietyTypes' => [
        'Indian Head',
        'Flying Eagle',
        'Lincoln Wheat',
        'Lincoln Memorial',
        'Liberty Cap Half Dime',
        'Seated Liberty Half Dime',
        'Liberty Cap Dime',
        'Seated Liberty Dime',
        'Barber Dime',
        'Winged Liberty Dime',
        'Roosevelt Dime',
        'Twenty Cent Piece',
        'Liberty Cap Quarter',
        'Seated Liberty Quarter',
        'Barber Quarter',
        'Standing Liberty',
        'Washington Quarter',
        'Seated Liberty Half Dollar',
        'Barber Half Dollar',
        'Walking Liberty',
        'Kennedy Half Dollar',
        'Franklin Half Dollar',
        'Seated Liberty Dollar',
        'Susan B Anthony Dollar',
        'Trade Dollar',
        'Morgan Dollar',
        'Peace Dollar',
        'Presidential Dollar',
        'Sacagawea Dollar',
        'Eisenhower Dollar',
        'Liberty Head Gold Dollar',
        'Indian Princess Gold Dollar',
        'Coronet Head Quarter Eagle',
        'Indian Princess Three Dollar',
        'Liberty Cap Half Eagle',
        'Turban Head Half Eagle',
        'Coronet Head Half Eagle',
        'Indian Head Half Eagle',
        'Coronet Head Eagle',
        'Saint Gaudens Double Eagle',
        'Coronet Head Double Eagle',
        'Commemorative Half Dollar',
        'Silver Dollar',
        'Tenth Ounce Gold',
        'Quarter Ounce Gold',
        'Half Ounce Gold',
        'One Ounce Gold',
        'Quarter Ounce Platinum'
    ],

    'mintsetTypes' => [
        'Westward Journey',
        'Lincoln Bicentennial',
        'Susan B Anthony Dollar',
        'Presidential Dollar',
        'Sacagawea Dollar',
        'Commemorative Half Dollar',
        'Tenth Ounce Gold',
        'Quarter Ounce Gold',
        'Half Ounce Gold',
        'One Ounce Gold',
        'Quarter Ounce Platinum'
    ],

    'folderTypes' => [
        'Flying Eagle',
        'Indian Head Nickel',
        'Westward Journey',
        'Jefferson Nickel',
        'Return to Monticello',
        'Lincoln Wheat',
        'Lincoln Memorial',
        'Lincoln Bicentennial',
        'Union Shield',
        'Winged Liberty Dime',
        'Roosevelt Dime',
        'Washington Quarter',
        'State Quarter',
        'Walking Liberty',
        'Kennedy Half Dollar',
        'Franklin Half Dollar',
        'Susan B Anthony Dollar',
        'Presidential Dollar',
        'Sacagawea Dollar',
        'Eisenhower Dollar'
    ],
    'rollTypes' => [
        'Flying Eagle',
        'Indian Head Nickel',
        'Westward Journey',
        'Jefferson Nickel',
        'Return to Monticello',
        'Lincoln Wheat',
        'Lincoln Memorial',
        'Lincoln Bicentennial',
        'Union Shield',
        'Winged Liberty Dime',
        'Roosevelt Dime',
        'Washington Quarter',
        'Walking Liberty',
        'Kennedy Half Dollar',
        'Franklin Half Dollar',
        'Susan B Anthony Dollar',
        'Presidential Dollar',
        'Sacagawea Dollar',
        'Eisenhower Dollar',
        'District of Columbia and US Territories',
        'State Quarter',
        'America the Beautiful Quarter'
    ],

    'boxTypes' => ['Indian Head Nickel',
        'Westward Journey',
        'Jefferson Nickel',
        'Return to Monticello',
        'Lincoln Wheat',
        'Lincoln Memorial',
        'Lincoln Bicentennial',
        'Union Shield',
        'Winged Liberty Dime',
        'Roosevelt Dime',
        'Washington Quarter',
        'Walking Liberty',
        'Kennedy Half Dollar',
        'Franklin Half Dollar',
        'Susan B Anthony Dollar',
        'Presidential Dollar',
        'Sacagawea Dollar',
        'Eisenhower Dollar',
        'District of Columbia and US Territories',
        'State Quarter',
        'America the Beautiful Quarter'
    ],

    'albumCategories' => ['Small Cent', 'Large Cent', 'Half Cent'],

    'fullTypes' => [
        'Jefferson Nickel',
        'Standing Liberty',
        'Winged Liberty Dime',
        'Franklin Half Dollar',
        'Roosevelt Dime'
    ],
    'satinTypes' => ['Lincoln Wheat',
        'Lincoln Memorial',
        'Lincoln Bicentennial',
        'Sacagawea Dollar'
    ],

    'cameoTypes' => ['Lincoln Wheat',
        'Lincoln Memorial', 'Jefferson Nickel', 'Winged Liberty Dime', 'Roosevelt Dime', 'Washington Quarter', 'Walking Liberty', 'Kennedy Half Dollar', 'Franklin Half Dollar', 'Susan B Anthony Dollar', 'Presidential Dollar', 'Sacagawea Dollar', 'Eisenhower Dollar', 'Commemorative Half Dollar', 'Silver Dollar', 'Tenth Ounce Gold', 'Quarter Ounce Gold', 'Half Ounce Gold', 'One Ounce Gold', 'Tenth Ounce Buffalo', 'Quarter Ounce Buffalo', 'Half Ounce Buffalo', 'One Ounce Buffalo', 'Tenth Ounce Platinum', 'Quarter Ounce Platinum', 'Half Ounce Platinum', 'One Ounce Platinum'],
    'ultraCameoTypes' => [
        'Lincoln Wheat',
        'Lincoln Memorial',
        'Jefferson Nickel',
        'Winged Liberty Dime',
        'Roosevelt Dime',
        'Washington Quarter',
        'Walking Liberty',
        'Kennedy Half Dollar',
        'Franklin Half Dollar',
        'Susan B Anthony Dollar',
        'Presidential Dollar',
        'Sacagawea Dollar',
        'Eisenhower Dollar',
        'Commemorative Half Dollar',
        'Silver Dollar',
        'Tenth Ounce Gold',
        'Quarter Ounce Gold',
        'Half Ounce Gold',
        'One Ounce Gold',
        'Tenth Ounce Buffalo',
        'Quarter Ounce Buffalo',
        'Half Ounce Buffalo',
        'One Ounce Buffalo',
        'Tenth Ounce Platinum',
        'Quarter Ounce Platinum',
        'Half Ounce Platinum',
        'One Ounce Platinum'
    ],
    'deepCameoTypes' => [
        'Lincoln Wheat',
        'Lincoln Memorial',
        'Jefferson Nickel',
        'Winged Liberty Dime',
        'Roosevelt Dime',
        'Washington Quarter',
        'Walking Liberty',
        'Kennedy Half Dollar',
        'Franklin Half Dollar',
        'Susan B Anthony Dollar',
        'Presidential Dollar',
        'Sacagawea Dollar',
        'Eisenhower Dollar',
        'Commemorative Half Dollar',
        'Silver Dollar',
        'Tenth Ounce Gold',
        'Quarter Ounce Gold',
        'Half Ounce Gold',
        'One Ounce Gold',
        'Tenth Ounce Buffalo',
        'Quarter Ounce Buffalo',
        'Half Ounce Buffalo',
        'One Ounce Buffalo',
        'Tenth Ounce Platinum',
        'Quarter Ounce Platinum',
        'Half Ounce Platinum',
        'One Ounce Platinum'
    ],

    'bieCoins' => ['7117', '7173', '7116', '7174', '7113', '7114', '7115', '7175', '7176', '7177', '7178', '7179', '7180', '7181', '7182', '7183', '7184', '7185', '7187', '7188', '7189', '7171', '7172'],

    'fortinTypes' => [],

    'lincolnwheatRPMCoins' => [
        '3668',
        '6909',
        '6910',
        '6911',
        '6912',
        '6913',
        '6915',
        '6916',
        '6917',
        '6918',
        '6919',
        '6920',
        '6921',
        '6922',
        '6923',
        '6924',
        '6925',
        '6926',
        '6927',
        '6928', '6929', '6930', '6931', '6932', '6933', '6934', '6935', '6936', '6937', '6938', '6939', '6940', '6941', '6942', '6943', '6944', '6945', '6946', '6947', '6948', '6949', '3765', '6985', '6986', '3773', '6977', '6978', '7186', '7191', '7192', '7298', '7299'],

    'bulkTypes' => [
        'Indian Head',
        'Flying Eagle',
        'Lincoln Wheat',
        'Lincoln Memorial',
        'Lincoln Bicentennial',
        'Union Sheild',
        'Shield Nickel',
        'Indian Head Nickel',
        'Westward Journey',
        'Jefferson Nickel',
        'Return to Monticello',
        'Seated Liberty Dime',
        'Barber Dime',
        'Winged Liberty Dime',
        'Roosevelt Dime',
        'State Quarter',
        'Barber Quarter',
        'Standing Liberty',
        'Washington Quarter',
        'Seated Liberty Half Dollar',
        'Barber Half Dollar',
        'Walking Liberty',
        'Kennedy Half Dollar',
        'Franklin Half Dollar',
        'Seated Liberty Dollar',
        'Susan B Anthony Dollar',
        'Trade Dollar',
        'Morgan Dollar',
        'Peace Dollar',
        'Presidential Dollar',
        'Sacagawea Dollar',
        'Eisenhower Dollar'
    ],

    'bullionTypes' => [
        'Liberty Head Gold Dollar',
        'Indian Princess Gold Dollar',
        'Coronet Head Quarter Eagle',
        'Indian Princess Three Dollar',
        'Liberty Cap Half Eagle',
        'Turban Head Half Eagle',
        'Coronet Head Half Eagle',
        'Indian Head Half Eagle',
        'Coronet Head Eagle',
        'Saint Gaudens Double Eagle',
        'Coronet Head Double Eagle',
        'Commemorative Half Dollar',
        'Silver Dollar',
        'Tenth Ounce Gold',
        'Quarter Ounce Gold',
        'Half Ounce Gold',
        'One Ounce Gold',
        'Quarter Ounce Platinum',
        'Tenth Ounce Buffalo',
        'Quarter Ounce Buffalo',
        'Half Ounce Buffalo',
        'One Ounce Buffalo'
    ],

    'seriesTypes' => [
        ''
    ],
    'grades_business' => [
        'MS-70',
        'MS-69',
        'MS-68',
        'MS-67',
        'MS-66',
        'MS-65',
        'MS-64',
        'MS-63',
        'MS-62',
        'MS-61',
        'MS-60',
        'AU-58',
        'AU-55',
        'AU-53',
        'MS-50',
        'EF-45',
        'EF-40',
        'VF-35',
        'VF-30',
        'VF-25',
        'VF-20',
        'F-15',
        'F-12',
        'VG-8',
        'G-4',
        'AG-3',
        'FR-2',
        'PO-1',
    ],
    'gradesProof' => [
        'PR-70',
        'PR-69',
        'PR-68',
        'PR-67',
        'PR-66',
        'PR-65',
        'PR-64',
        'PR-63',
        'PR-62',
        'PR-61',
        'PR-60',
        'PR-58',
        'PR-55',
        'PR-50',
        'PR-45',
        'PR-40',
        'PR-35',
    ],
     'centColors' => [
         'RD',
         'RB',
         'BN'
     ]

];